SIMS_IT0602/Models/Course.cs
using System;
namespace SIMS_IT0602.Models
{
	public class Course
	{
		public int Id { get; set; }
		public String Name { get; set; }
		public int Lecturer { get; set; }
		public Course()
		{
		}
	}
}

SIMS_IT0602/Models/ErrorViewModel.cs
namespace SIMS_IT0602.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SIMS_IT0602/Models/Teacher.cs
using System;
namespace SIMS_IT0602.Models
{
	public class Teacher
	{
		public int Id { get; set; }
		public String Name { get; set; }
		public DateTime DoB { get; set; }
		public Teacher()
		{
		}
	}
}

SIMS_IT0602/Models/User.cs
using System;
namespace SIMS_IT0602.Models
{
	public class User
	{
		public int Id { get; set; }
		public String UserName { get; set; }
		public String Pass { get; set; }
		public String Role { get; set; }
		public User()
		{
		}
	}
}

SIMS_IT0602/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SIMS_IT0602.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SIMS_IT0602.Controllers
{
    public class AuthenticationController : Controller
    {
        [HttpPost]
        public IActionResult Login(User user)
        {
            //read file users.json
            List<User>? users = LoadUsersFromFile("users.json");
            var result = users.
                        FirstOrDefault(u => u.UserName == user.UserName
                                && u.Pass == user.Pass);
            if (result != null)
            {
                HttpContext.Session.SetString("UserName", result.UserName);
                HttpContext.Session.SetString("Role", result.Role);
                return RedirectToAction("Index", "Teacher");
            }
            else
            {
                ViewBag.error = "Invalid user!";
                return View("Login");
            }
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        public List<User>? LoadUsersFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText(fileName);
            return JsonSerializer.Deserialize<List<User>>(readText);
        }
    }
}

SIMS_IT0602/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SIMS_IT0602.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SIMS_IT0602.Controllers
{
    public class CourseController : Controller
    {
        static List<Course> courses = new List<Course>();
        [HttpPost]
        public IActionResult CreateCourse(Course course)
        {
            courses.Add(course);
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(courses, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("course.json"))
            {
                writer.Write(jsonString);
            }

            return Content(jsonString);
        }

        [HttpGet]
        public IActionResult CreateCourse()
        {
            List<Teacher>? teachers = LoadTeacherFromFile("data.json");

            ViewBag.SelectTeacher = teachers;
            return View();
        }

        public List<Teacher>? LoadTeacherFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText(fileName);
            return JsonSerializer.Deserialize<List<Teacher>>(readText);
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

SIMS_IT0602/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SIMS_IT0602.Models;

namespace SIMS_IT0602.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SIMS_IT0602/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SIMS_IT0602.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SIMS_IT0602.Controllers
{
    public class TeacherController : Controller
    {
        static List<Teacher> teachers = new List<Teacher>();

        public IActionResult Delete(int Id)
        {
            var teachers = LoadTeacherFromFile("data.json");

            //find teacher in an array
            var searchTeacher = teachers.FirstOrDefault(t => t.Id == Id);
            teachers.Remove(searchTeacher);

            //save to file
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("data.json"))
            {
                writer.Write(jsonString);
            }
            return RedirectToAction("Index");

        }

        [HttpPost] //submit new Teacher
        public IActionResult NewTeacher(Teacher teacher)
        {
            teachers.Add(teacher);
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("data.json"))
            {
                writer.Write(jsonString);
            }

            return Content(jsonString);
        }

        [HttpGet] //click hyperlink
        public IActionResult NewTeacher()
        {
            return View();
        }
        public List<Teacher>? LoadTeacherFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText("data.json");
            return JsonSerializer.Deserialize<List<Teacher>>(readText);
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
            // Read a file
            teachers = LoadTeacherFromFile("data.json");
            return View(teachers);
        }
    }
}

SIMS_IT0602/Views/Authentication/Login.cshtml
@model User
<h1 style="color:orange">New Teacher</h1>

@using (Html.BeginForm("Login", "Authentication", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.UserName,
            new { placeholder = "User Name", Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Pass, new { Class = "control-label" })
        @Html.PasswordFor(m => m.Pass,
            new { placeholder = "Password", Class = "form-control" })
    </div>
    <div style="color:red">
        @ViewBag.error
    </div>
    <br />
    <input type="submit" value="Login" class="btn btn-primary" />

}

SIMS_IT0602/Views/Course/CreateCourse.cshtml
@model Course
<h1 style="color:orange">New Course</h1>

@using (Html.BeginForm("CreateCourse", "Course", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Id, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Id, new { Class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Name, new { Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Lecturer, new { Class = "control-label" })
        @Html.DropDownListFor(m=>m.Lecturer, new SelectList(ViewBag.SelectTeacher, "Id", "Name"))
    </div>
    <input type="submit" value="Create Course" class="btn btn-primary" />

}

SIMS_IT0602/Views/Course/Index.cshtml
<h1>Course homepage</h1>
<a asp-action="CreateCourse" asp-controller="Course">Create Course</a>

SIMS_IT0602/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SIMS_IT0602/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SIMS_IT0602</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SIMS_IT0602.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SIMS_IT0602</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Manage Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Manage Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Course" asp-action="Index">Manage Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Authentication" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SIMS_IT0602 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SIMS_IT0602/Views/Teacher/Index.cshtml
@model IEnumerable<Teacher>
<h1>Hello World @ViewBag.UserName , you are @ViewBag.Role</h1>
<table class="table">
    <thead>
        <tr>
            <td>Name</td>
            <td>Date of Birth</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.DoB</td>
                    <td>
                        <a class="btn btn-sm btn-primary"
                           href="@Url.Action("Delete","Teacher",new {id=item.Id})">Delete</a>
                    </td>
                </tr>
        }
    </tbody>
</table>
<ul>
   

</ul>
<ul>
    <li>
        <a asp-controller="Teacher" asp-action="NewTeacher">New Teacher</a>
    </li>
</ul>

SIMS_IT0602/Views/Teacher/NewTeacher.cshtml
@model Teacher
<h1 style="color:orange">New Teacher</h1>

@using (Html.BeginForm("NewTeacher", "Teacher", FormMethod.Post))
{
        <div class="form-group">
            @Html.LabelFor(m => m.Id, new { Class = "control-label" })
            @Html.TextBoxFor(m => m.Id, new {Class= "form-control" })
        </div>
    
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { Class = "control-label" })
            @Html.TextBoxFor(m => m.Name, new { Class = "form-control" })
        </div>
        <div class="form-group">
             @Html.LabelFor(m => m.DoB,  new { Class = "control-label" })
             @Html.TextBoxFor(m => m.DoB, new { Class = "form-control" })
        </div>
        <input type="submit" value="Create" class="btn btn-primary" />
     
  }